version: '3'
services:
    web:
    webgui:
        image: jameszezhan/converter-gui:latest
        ports: 
            - "8081:8080"
    apiservice:
        image: jameszezhan/converter-api:latest
        ports: 
            - "8080:8080"
        environment:
            GOOGLE_CLIENT_ID: ${YOUR_GOOGLE_CLIENT_ID}
            GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
            GOOGLE_SCOPE: https://www.googleapis.com/auth/youtube.readonly
            GOOGLE_AUTH_URL: https://accounts.google.com/o/oauth2/v2/auth
            GOOGLE_TOKEN_URL: https://oauth2.googleapis.com/token
            GOOGLE_REDIRECT_URL: http://localhost:8080/api/v1/youtube #this is for deploying locally
            SPOTIFY_CLIENT_ID: ${YOUR_SPOTIFY_CLIENT_ID}
            SPOTIFY_CLIENT_SECRET: ${SPOTIFY_CLIENT_SECRET}
            SPOTIFY_SCOPE: user-read-email playlist-modify-private
            SPOTIFY_AUTH_URL: https://accounts.spotify.com/authorize
            SPOTIFY_TOKEN_URL: https://accounts.spotify.com/api/token
            SPOTIFY_REDIRECT_URL: http://localhost:8080/api/v1/spotify #this is for deploying locally
        command: "/opt/app/start.sh"
