spring:
  config:
    activate:
      on-profile: prod
GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
GOOGLE_SCOPE: https://www.googleapis.com/auth/youtube.readonly
GOOGLE_AUTH_URL: https://accounts.google.com/o/oauth2/v2/auth
GOOGLE_TOKEN_URL: https://oauth2.googleapis.com/token
GOOGLE_REDIRECT_URL: ${GOOGLE_REDIRECT_URL}
SPOTIFY_CLIENT_ID: ${SPOTIFY_CLIENT_ID}
SPOTIFY_CLIENT_SECRET: ${SPOTIFY_CLIENT_SECRET}
SPOTIFY_SCOPE: user-read-email playlist-modify-private
SPOTIFY_AUTH_URL: https://accounts.spotify.com/authorize
SPOTIFY_TOKEN_URL: https://accounts.spotify.com/api/token
SPOTIFY_REDIRECT_URL: ${SPOTIFY_REDIRECT_URL}
server:
  port: 8089